# Generated by Django 3.1.7 on 2021-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.FloatField(verbose_name='X')),
                ('Y', models.FloatField(verbose_name='Y')),
                ('UniqueSquirrelID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Hectare', models.CharField(max_length=255, verbose_name='Hectare')),
                ('Shift', models.CharField(max_length=255, verbose_name='Shift')),
                ('Date', models.DateField(verbose_name='Date')),
                ('HectareSquirrelNumber', models.IntegerField(verbose_name='HectareSquirrelNumber')),
                ('Age', models.CharField(max_length=255, verbose_name='Age')),
                ('PrimaryFurColor', models.CharField(max_length=255, verbose_name='PrimaryFurColor')),
                ('HighlightFurColor', models.CharField(max_length=255, verbose_name='HighlightFurColor')),
                ('CombinationOfPrimaryAndHighlightColor', models.CharField(max_length=255, verbose_name='CombinationOfPrimaryAndHighlightColor')),
                ('ColorNotes', models.CharField(max_length=255, verbose_name='ColorNotes')),
                ('Location', models.CharField(max_length=255, verbose_name='Location')),
                ('AboveGroundSighterMeasurement', models.CharField(max_length=255, verbose_name='AboveGroundSighterMeasurement')),
                ('SpecificLocation', models.CharField(max_length=255, verbose_name='SpecificLocation')),
                ('Running', models.BooleanField(verbose_name='Running')),
                ('Chasing', models.BooleanField(verbose_name='Chasing')),
                ('Climbing', models.BooleanField(verbose_name='Climbing')),
                ('Eating', models.BooleanField(verbose_name='Eating')),
                ('Foraging', models.BooleanField(verbose_name='Foraging')),
                ('OtherActivities', models.CharField(max_length=255, verbose_name='OtherActivities')),
                ('Kuks', models.BooleanField(verbose_name='Kuks')),
                ('Quaas', models.BooleanField(verbose_name='Quaas')),
                ('Moans', models.BooleanField(verbose_name='Moans')),
                ('TailFlags', models.BooleanField(verbose_name='TailFlags')),
                ('TailTwitches', models.BooleanField(verbose_name='TailTwitches')),
                ('Approaches', models.BooleanField(verbose_name='Approaches')),
                ('Indifferent', models.BooleanField(verbose_name='Indifferent')),
                ('RunsFrom', models.BooleanField(verbose_name='RunsFrom')),
                ('OtherInteractions', models.CharField(max_length=255, verbose_name='OtherInteractions')),
                ('LatLong', models.CharField(max_length=255, verbose_name='Latlong')),
            ],
        ),
    ]
